### Importing necessary modules

In [1]:
import pandas as pd                                                                     # type: ignore
import matplotlib.pyplot as plt                                                         # type: ignore
import seaborn as sns                                                                   # type: ignore
import numpy as np                                                                      # type: ignore
from  sklearn import metrics                                                            # type: ignore
from sklearn.preprocessing import StandardScaler                                        # type: ignore
from sklearn.metrics import roc_auc_score, roc_curve, brier_score_loss                  # type: ignore
from sklearn.metrics import average_precision_score                                     # type: ignore
import tensorflow as tf                                                                 # type: ignore
from sklearn.model_selection import train_test_split                                    # type: ignore
import matplotlib as mpl                                                                # type: ignore
colors = plt.rcParams['axes.prop_cycle'].by_key()['color']
mpl.rcParams['figure.figsize'] = (9, 7)
from joblib import dump, load                                                           # type: ignore
import random
import cartopy                                                                          # type: ignore
from matplotlib.offsetbox import AnchoredText                                           # type: ignore
import cartopy.crs as ccrs                                                              # type: ignore
import cartopy.feature as cfeature                                                      # type: ignore

2024-06-13 10:30:30.809876: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-13 10:30:30.814567: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-13 10:30:30.872319: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-13 10:30:32.207472: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
Dakar_lon = -17.467686
Dakar_lat = 14.716677

In [3]:
import sys
sys.path.insert(1, "/home/mendrika/mendrika-phd/codes/nflics")
import nflics

### Importing dataset

In [4]:
test_data = pd.read_csv("/home/mendrika/mendrika-phd/codes/nflics/output/SM2024-06-13/raw-artificial-data-two-storms-same-size-and-wp-different-t0-and-location.csv", index_col=False)
raw_test_data = test_data.copy()

In [5]:
pcX0 = pd.read_csv(f"/home/mendrika/mendrika-phd/codes/nflics/output/SM2024-06-13/pcX0-two-storms-same-size-and-wp-different-t0-and-location.csv", index_col=None)
to_keep = pcX0["index"].values
to_drop = [i for i in range(len(test_data)) if i not in to_keep]

In [6]:
test_data = test_data.drop(index=to_drop)
raw_test_data = raw_test_data.drop(index=to_drop)

#### Choosing field to include in the data

In [7]:
# Presence or absence of convection in Dakar at time t+1
target_index = "Cb_Dakar"

# Input at time t0
t0 = "year,month,day,hour,minute,"

# latitude and longitude, wavelet power, storm size and distance to Dakar
location = ""
wavelet_power = ""
storm_size = ""
distance = ""
for i in range(1,6):
    location += f"lat{i},lon{i},"
    wavelet_power += f"wp{i},"
    distance += f"ds{i},"
    storm_size += f"size{i},"

# combining all fields to form the feature input
features = t0 + location + wavelet_power + storm_size + distance
field =  features + target_index
field = field.split(',')

### Exploratory data analysis

In [8]:
def log_transform(df, keys):
    df_copy = df.copy()    
    for key in keys:
        transformed = []
        for i in df_copy[key]:
            if i > 0:
                transformed.append(np.log(i))
            else:
                transformed.append(np.log(i+1e-8))    
        df_copy[key] = transformed
    return df_copy

In [9]:
def sqrt_transform(df, keys):
    df_copy = df.copy()    
    for key in keys:
        transformed = []
        for i in df_copy[key]:
            if i >= 0:
                transformed.append(np.sqrt(i)) 
        df_copy[key] = transformed
    return df_copy

In [10]:
to_scale = wavelet_power + storm_size + distance

In [11]:
test_data = log_transform(test_data, to_scale.split(',')[:-1])
test_data = sqrt_transform(test_data, t0.split(',')[:-1])

In [12]:
model = tf.keras.models.load_model("/home/mendrika/mendrika-phd/codes/nflics/model-ML-Dakar/best_model_new_format_Dakar_nearest5_corrected.keras")

In [13]:
scaler = load('std_scaler_best_model_new_format_Dakar_nearest5_corrected.bin')

In [14]:
x_test = test_data[features.split(",")[:-1]]
x_test_std = scaler.transform(x_test)

In [30]:
y_pred_nn = model.predict(x_test_std)

31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [31]:
y_pred_nn = y_pred_nn.flatten()

### Unconditional

In [17]:
pc = pd.read_csv("/home/mendrika/mendrika-phd/codes/nflics/unconditional-probability/dataset-pc-31.csv")

In [35]:
Cb_Dakar_unc = []
for i in range(len(raw_test_data)):
    minute = raw_test_data["minute"].values[i]    
    hour = raw_test_data["hour"].values[i] + 1
    if hour != 24:    
        index_hour = pc["hour"].values == hour
    else:
        index_hour = pc["hour"].values == 0
    index_minute = pc["minute"].values == minute
    index = index_hour * index_minute
    Cb_Dakar_unc.append(pc["probability"].values[index])
y_pred_clim = np.array(Cb_Dakar_unc).flatten()

In [26]:
y_pred_nflics = pcX0["pcX0"].values

In [36]:
index_comp_nflics = y_pred_nflics < y_pred_nn
index_comp_clim = y_pred_clim < y_pred_nn

In [37]:
df_selected_nflics = raw_test_data.loc[index_comp_nflics]
df_selected_clim = raw_test_data.loc[index_comp_clim]

In [38]:
df_selected_nflics

,year,month,day,hour,minute,lat1,lon1,lat2,lon2,lat3,...,size1,size2,size3,size4,size5,ds1,ds2,ds3,ds4,ds5
20,2008,8,3,13,0,14.069591,-17.292319,14.224282,-10.062736,14,...,5000.0,5000.0,0,0,0,22.2036,251.3901,430,430,430
70,2010,8,20,21,0,17.937526,-15.713984,16.087302,-17.627783,14,...,5000.0,5000.0,0,0,0,130.1730,47.0106,430,430,430
75,2008,7,24,11,0,10.079470,-11.681875,12.202506,-12.258080,14,...,5000.0,5000.0,0,0,0,246.7590,190.5151,430,430,430
99,2006,8,14,21,0,14.792024,-17.996106,14.014509,-13.986191,14,...,5000.0,5000.0,0,0,0,18.2483,117.2774,430,430,430
108,2017,8,27,10,0,12.638838,-10.385815,10.243078,-11.774612,14,...,5000.0,5000.0,0,0,0,247.1214,241.2302,430,430,430
119,2014,8,2,10,0,17.962123,-17.839497,10.865586,-12.442059,14,...,5000.0,5000.0,0,0,0,111.0045,209.4684,430,430,430
152,2014,8,21,16,0,13.758409,-17.138268,14.533483,-10.161784,14,...,5000.0,5000.0,0,0,0,33.9559,248.0181,430,430,430
188,2014,7,11,7,0,14.946904,-17.026998,15.098594,-17.533666,14,...,5000.0,5000.0,0,0,0,17.0000,13.0384,430,430,430
200,2017,7,12,5,0,17.670745,-10.711488,10.957398,-17.084251,14,...,5000.0,5000.0,0,0,0,258.3041,132.0152,430,430,430
207,2016,6,16,5,0,11.913448,-16.447004,15.777255,-10.029201,14,...,5000.0,5000.0,0,0,0,101.3903,258.1182,430,430,430
211,2006,8,13,22,0,16.031803,-17.695470,16.360909,-12.768546,14,...,5000.0,5000.0,0,0,0,45.0999,172.7542,430,430,430
219,2004,8,17,13,0,17.925074,-15.550686,13.454552,-13.614532,14,...,5000.0,5000.0,0,0,0,133.4054,132.8157,430,430,430
220,2014,6,29,7,0,14.738231,-17.136525,15.774424,-15.697481,14,...,5000.0,5000.0,0,0,0,11.0454,72.7186,430,430,430
240,2014,6,15,11,0,17.962871,-11.489043,10.953166,-10.547706,14,...,5000.0,5000.0,0,0,0,238.9477,262.4576,430,430,430
263,2013,6,6,10,0,12.431708,-11.624002,10.862585,-12.019883,14,...,5000.0,5000.0,0,0,0,208.1658,220.6015,430,430,430
267,2013,8,25,11,0,13.838169,-13.853547,14.473476,-10.345227,14,...,5000.0,5000.0,0,0,0,122.4827,241.0519,430,430,430
296,2013,8,22,1,0,13.787081,-17.326511,12.909213,-13.355577,14,...,5000.0,5000.0,0,0,0,32.0156,147.2311,430,430,430
305,2010,8,15,8,0,14.727194,-17.639891,16.452275,-12.333245,14,...,5000.0,5000.0,0,0,0,6.0000,187.5447,430,430,430
328,2018,8,5,12,0,11.702549,-10.295663,13.453786,-13.115893,14,...,5000.0,5000.0,0,0,0,259.3318,149.0403,430,430,430
332,2013,6,18,13,0,10.634550,-14.381187,13.537246,-12.829255,14,...,5000.0,5000.0,0,0,0,170.2939,157.8924,430,430,430
334,2008,8,4,8,0,10.155505,-11.644219,11.209120,-17.355458,14,...,5000.0,5000.0,0,0,0,246.2214,123.1990,430,430,430
338,2005,8,6,13,0,10.706940,-15.157723,11.181504,-12.462153,14,...,5000.0,5000.0,0,0,0,155.2063,202.0025,430,430,430
347,2011,7,29,1,0,16.351082,-17.246928,11.287441,-10.342418,14,...,5000.0,5000.0,0,0,0,58.2495,263.8560,430,430,430
359,2018,6,29,0,0,13.933197,-17.506951,11.586542,-12.693289,14,...,5000.0,5000.0,0,0,0,27.2947,188.0957,430,430,430
408,2008,6,16,7,0,17.133436,-12.887386,10.323338,-12.663895,14,...,5000.0,5000.0,0,0,0,181.6480,216.3747,430,430,430
424,2012,8,30,11,0,11.647129,-12.765966,16.572313,-17.804384,14,...,5000.0,5000.0,0,0,0,185.3106,64.1950,430,430,430
430,2004,8,17,5,0,14.363257,-17.970066,12.406250,-17.318246,14,...,5000.0,5000.0,0,0,0,22.2036,81.0247,430,430,430
440,2017,6,21,22,0,14.563353,-16.942123,13.884359,-17.563135,14,...,5000.0,5000.0,0,0,0,17.7200,29.6142,430,430,430
450,2005,8,21,11,0,13.231719,-13.279168,13.992789,-12.721370,14,...,5000.0,5000.0,0,0,0,145.4991,159.6653,430,430,430
489,2004,7,4,11,0,10.258615,-15.461948,17.906642,-11.665168,14,...,5000.0,5000.0,0,0,0,165.7468,232.7230,430,430,430
496,2005,8,9,11,0,11.564823,-12.191669,14.618197,-10.064359,14,...,5000.0,5000.0,0,0,0,202.7856,251.0000,430,430,430
503,2013,6,8,8,0,17.633703,-13.233653,17.266203,-12.300429,14,...,5000.0,5000.0,0,0,0,181.3946,202.1410,430,430,430
517,2006,6,13,2,0,16.407109,-17.879287,16.164497,-11.879625,14,...,5000.0,5000.0,0,0,0,58.5491,199.1808,430,430,430
523,2017,8,30,8,0,16.900596,-13.412590,17.742379,-13.443677,14,...,5000.0,5000.0,0,0,0,161.5333,178.0028,430,430,430
525,2008,8,12,10,0,12.682940,-11.880158,11.285470,-10.559558,14,...,5000.0,5000.0,0,0,0,196.5121,256.7255,430,430,430
548,2010,6,15,6,0,15.217928,-17.958375,11.206923,-14.610593,14,...,5000.0,5000.0,0,0,0,22.6716,149.8433,430,430,430
564,2012,6,19,12,0,16.792224,-12.822603,10.326067,-12.472401,14,...,5000.0,5000.0,0,0,0,178.1011,220.6581,430,430,430
637,2007,6,13,12,0,13.662186,-13.696512,10.291116,-14.406115,14,...,5000.0,5000.0,0,0,0,128.8449,179.3878,430,430,430
652,2009,8,22,5,0,16.089721,-17.313811,13.727316,-13.788050,14,...,5000.0,5000.0,0,0,0,48.8365,125.4193,430,430,430
679,2009,6,24,12,0,11.532593,-17.858219,11.873589,-11.236438,14,...,5000.0,5000.0,0,0,0,113.3578,226.7907,430,430,430
692,2014,8,2,9,0,14.190715,-17.664422,14.950562,-12.451386,14,...,5000.0,5000.0,0,0,0,20.1246,170.2939,430,430,430
753,2012,6,8,12,0,10.142678,-11.870709,14.208921,-17.763379,14,...,5000.0,5000.0,0,0,0,240.1687,21.6333,430,430,430
765,2005,7,6,4,0,14.688570,-17.725239,11.861065,-15.516651,14,...,5000.0,5000.0,0,0,0,9.0554,114.2366,430,430,430
775,2011,6,25,22,0,14.924586,-17.645251,15.966935,-10.856650,14,...,5000.0,5000.0,0,0,0,9.2195,231.6139,430,430,430
778,2017,8,5,10,0,13.611094,-17.877846,10.144408,-10.011230,14,...,5000.0,5000.0,0,0,0,42.5441,292.3696,430,430,430
784,2005,7,4,7,0,10.281245,-15.859904,11.661982,-12.790358,14,...,5000.0,5000.0,0,0,0,160.5895,183.9185,430,430,430
828,2011,7,15,19,0,15.615395,-17.402334,11.686055,-10.731778,14,...,5000.0,5000.0,0,0,0,31.4006,246.0589,430,430,430
865,2018,7,4,7,0,17.528792,-11.412276,17.214510,-11.666629,14,...,5000.0,5000.0,0,0,0,233.4973,220.7374,430,430,430
885,2004,8,11,3,0,14.004530,-16.479054,16.043021,-13.178813,14,...,5000.0,5000.0,0,0,0,38.4187,154.6383,430,430,430
890,2012,8,1,3,0,16.378361,-17.423107,12.826673,-13.083442,14,...,5000.0,5000.0,0,0,0,57.4282,156.6684,430,430,430
907,2008,7,5,8,0,14.001416,-17.051174,12.358573,-12.680995,14,...,5000.0,5000.0,0,0,0,26.4008,175.7754,430,430,430
920,2008,8,29,8,0,11.992617,-17.745186,17.415572,-10.046858,14,...,5000.0,5000.0,0,0,0,96.6902,275.2817,430,430,430
938,2007,7,24,9,0,15.500829,-17.915916,15.927838,-13.705045,14,...,5000.0,5000.0,0,0,0,29.9666,136.2975,430,430,430
972,2013,8,23,12,0,13.228401,-12.765693,13.341350,-17.276744,14,...,5000.0,5000.0,0,0,0,162.8650,48.0416,430,430,430
979,2017,7,26,10,0,14.127260,-10.447929,13.892023,-10.368366,14,...,5000.0,5000.0,0,0,0,237.6089,240.4101,430,430,430
995,2007,6,7,3,0,14.198026,-17.123993,13.212858,-13.569866,14,...,5000.0,5000.0,0,0,0,19.2354,136.4881,430,430,430

In [40]:
df_selected_clim

,year,month,day,hour,minute,lat1,lon1,lat2,lon2,lat3,...,size1,size2,size3,size4,size5,ds1,ds2,ds3,ds4,ds5
20,2008,8,3,13,0,14.069591,-17.292319,14.224282,-10.062736,14,...,5000.0,5000.0,0,0,0,22.2036,251.3901,430,430,430
43,2006,7,6,11,0,13.648312,-16.722110,17.693135,-11.299074,14,...,5000.0,5000.0,0,0,0,41.6773,240.1687,430,430,430
99,2006,8,14,21,0,14.792024,-17.996106,14.014509,-13.986191,14,...,5000.0,5000.0,0,0,0,18.2483,117.2774,430,430,430
106,2005,8,10,20,0,14.450480,-16.503082,15.448891,-17.889227,14,...,5000.0,5000.0,0,0,0,32.2800,27.7308,430,430,430
125,2009,6,2,21,0,14.420235,-16.710983,14.548392,-14.114321,14,...,5000.0,5000.0,0,0,0,26.0000,112.0714,430,430,430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,2009,8,24,12,0,15.329425,-15.782273,15.288948,-12.412143,14,...,5000.0,5000.0,0,0,0,62.0322,173.4013,430,430,430
907,2008,7,5,8,0,14.001416,-17.051174,12.358573,-12.680995,14,...,5000.0,5000.0,0,0,0,26.4008,175.7754,430,430,430
938,2007,7,24,9,0,15.500829,-17.915916,15.927838,-13.705045,14,...,5000.0,5000.0,0,0,0,29.9666,136.2975,430,430,430
978,2011,8,28,12,0,15.848584,-16.296669,13.931740,-16.449457,14,...,5000.0,5000.0,0,0,0,58.0000,41.1096,430,430,430
995,2007,6,7,3,0,14.198026,-17.123993,13.212858,-13.569866,14,...,5000.0,5000.0,0,0,0,19.2354,136.4881,430,430,430